.PHONY: clean All

All:
	@echo "----------Building project:[ FunctionRunFun - Debug ]----------"
	@$(MAKE) -f  "FunctionRunFun.mk"
clean:
	@echo "----------Cleaning project:[ FunctionRunFun - Debug ]----------"
	@$(MAKE) -f  "FunctionRunFun.mk" clean
