.PHONY: clean All

All:
	@echo "----------Building project:[ HeavyCargo - Debug ]----------"
	@$(MAKE) -f  "HeavyCargo.mk"
clean:
	@echo "----------Cleaning project:[ HeavyCargo - Debug ]----------"
	@$(MAKE) -f  "HeavyCargo.mk" clean
