.PHONY: clean All

All:
	@echo "----------Building project:[ Lanterns - Debug ]----------"
	@$(MAKE) -f  "Lanterns.mk"
clean:
	@echo "----------Cleaning project:[ Lanterns - Debug ]----------"
	@$(MAKE) -f  "Lanterns.mk" clean
